/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangIndustriesRouteImport } from './routes/$lang.industries'
import { Route as LangServicesRouteImport } from './routes/$lang.services'
import { Route as LangCaseStudiesIndexRouteImport } from './routes/$lang.case-studies.index'
import { Route as LangCaseStudiesSlugRouteImport } from './routes/$lang.case-studies.$slug'
import { Route as LangLegalDocRouteImport } from './routes/$lang.legal.$doc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangIndustriesRoute = LangIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => LangRoute,
} as any)
const LangServicesRoute = LangServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LangRoute,
} as any)
const LangCaseStudiesIndexRoute = LangCaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => LangRoute,
} as any)
const LangCaseStudiesSlugRoute = LangCaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangLegalDocRoute = LangLegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/industries': typeof LangIndustriesRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/case-studies/$slug': typeof LangCaseStudiesSlugRoute
  '/$lang/legal/$doc': typeof LangLegalDocRoute
  '/$lang/case-studies/': typeof LangCaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/industries': typeof LangIndustriesRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/case-studies/$slug': typeof LangCaseStudiesSlugRoute
  '/$lang/legal/$doc': typeof LangLegalDocRoute
  '/$lang/case-studies': typeof LangCaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/industries': typeof LangIndustriesRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/case-studies/$slug': typeof LangCaseStudiesSlugRoute
  '/$lang/legal/$doc': typeof LangLegalDocRoute
  '/$lang/case-studies/': typeof LangCaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/industries'
    | '/$lang/services'
    | '/$lang/'
    | '/$lang/case-studies/$slug'
    | '/$lang/legal/$doc'
    | '/$lang/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/industries'
    | '/$lang/services'
    | '/$lang'
    | '/$lang/case-studies/$slug'
    | '/$lang/legal/$doc'
    | '/$lang/case-studies'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/industries'
    | '/$lang/services'
    | '/$lang/'
    | '/$lang/case-studies/$slug'
    | '/$lang/legal/$doc'
    | '/$lang/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/industries': {
      id: '/$lang/industries'
      path: '/industries'
      fullPath: '/$lang/industries'
      preLoaderRoute: typeof LangIndustriesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/services': {
      id: '/$lang/services'
      path: '/services'
      fullPath: '/$lang/services'
      preLoaderRoute: typeof LangServicesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/case-studies/': {
      id: '/$lang/case-studies/'
      path: '/case-studies'
      fullPath: '/$lang/case-studies/'
      preLoaderRoute: typeof LangCaseStudiesIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/case-studies/$slug': {
      id: '/$lang/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/$lang/case-studies/$slug'
      preLoaderRoute: typeof LangCaseStudiesSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/legal/$doc': {
      id: '/$lang/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/$lang/legal/$doc'
      preLoaderRoute: typeof LangLegalDocRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangIndustriesRoute: typeof LangIndustriesRoute
  LangServicesRoute: typeof LangServicesRoute
  LangIndexRoute: typeof LangIndexRoute
  LangCaseStudiesSlugRoute: typeof LangCaseStudiesSlugRoute
  LangLegalDocRoute: typeof LangLegalDocRoute
  LangCaseStudiesIndexRoute: typeof LangCaseStudiesIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangIndustriesRoute: LangIndustriesRoute,
  LangServicesRoute: LangServicesRoute,
  LangIndexRoute: LangIndexRoute,
  LangCaseStudiesSlugRoute: LangCaseStudiesSlugRoute,
  LangLegalDocRoute: LangLegalDocRoute,
  LangCaseStudiesIndexRoute: LangCaseStudiesIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
